const schemas = {};

schemas.actionStatusType = require('./schema/action-status-type.json')
schemas.action = require('./schema/action.json')
schemas.administrativeArea = require('./schema/administrative-area.json')
schemas.aggregateRating = require('./schema/aggregate-rating.json')
schemas.audience = require('./schema/audience.json')
schemas.boolean = require('./schema/boolean.json')
schemas.brand = require('./schema/brand.json')
schemas.class = require('./schema/class.json')
schemas.contactPoint = require('./schema/contact-point.json')
schemas.contactPointOption = require('./schema/contact-point-option.json')
schemas.country = require('./schema/country.json')
schemas.creativeWork = require('./schema/creative-work.json')
schemas.educationalOrganization = require('./schema/educational-organization.json')
schemas.dateTime = require('./schema/date-time.json')
schemas.date = require('./schema/date.json')
schemas.dayOfWeek = require('./schema/day-of-week.json')
schemas.distance = require('./schema/distance.json')
schemas.duration = require('./schema/duration.json')
schemas.entryPoint = require('./schema/entry-point.json')
schemas.enumeration = require('./schema/enumeration.json')
schemas.event = require("./schema/event.json");
schemas.geoCoordinates = require("./schema/geo-coordinates.json");
schemas.geoShape = require("./schema/geo-shape.json");
schemas.imageObject = require('./schema/image-object.json')
schemas.integer = require('./schema/integer.json')
schemas.itemListOrderType = require('./schema/item-list-order-type.json')
schemas.language = require('./schema/language.json')
schemas.listItem = require('./schema/list-item.json')
schemas.locationFeatureSpecification = require('./schema/location-feature-specification.json')
schemas.map = require('./schema/map.json')
schemas.mapCategoryType = require('./schema/map-category-type.json')
schemas.number = require('./schema/number.json')
schemas.offerCatalog = require('./schema/offer-catalog.json')
schemas.openingHoursSpecification = require('./schema/opening-hours-specification.json')
schemas.organization = require('./schema/organization.json')
schemas.person = require('./schema/person.json')
schemas.photograph = require('./schema/photograph.json')
schemas.place = require('./schema/place.json')
schemas.postalAddress = require('./schema/postal-address.json')
schemas.propertyValue = require('./schema/property-value.json')
schemas.property = require('./schema/property.json')
schemas.product = require('./schema/product.json')
schemas.qualitativeValue = require('./schema/qualitative-value.json')
schemas.quantitativeValue = require('./schema/quantitative-value.json')
schemas.review = require('./schema/review.json')
schemas.serviceChannel = require('./schema/service-channel.json')
schemas.service = require('./schema/service.json')
schemas.structuredValue = require('./schema/structured-value.json')
schemas.text = require("./schema/text.json");
schemas.thing = require('./schema/thing.json')
schemas.time = require('./schema/time.json')
schemas.url = require("./schema/url.json");


const definitions = JSON.parse(JSON.stringify(schemas))
schemas.definitions = definitions;

module.exports = schemas;
